version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./workflows:/app/workflows
    env_file:
      - .env
    ports:
      - '8000:8000'
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    depends_on:
      - backend
